
name: Terraform CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  TF_VERSION: 1.6.6

jobs:
  plan:
    name: Terraform Plan (dev)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init (dev)
        run: terraform init
        working-directory: envs/dev

      - name: Terraform Plan (dev)
        run: terraform plan
        working-directory: envs/dev

  apply:
    name: Terraform Apply (dev - manual)
    needs: plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production   # ðŸ‘ˆ approval manuelle

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init (dev)
        run: terraform init
        working-directory: envs/dev

      - name: Terraform Apply (dev)
        run: terraform apply -auto-approve
        working-directory: envs/dev
